### ISSUE TITLE
Unfollow error

### ISSUE THREAD

**Issue by dragonqfly** [andrewsegas/instaboost#1]
Hi, I'm trying the program and it's very good, but it does not unfollow. In the file errors.log, it gives me the following code:

ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "src\instabot.py", line 935, in auto_unfollow
KeyError: 'user'

Thanks in advance for the attention

**Comment by andrewsegas** [comment]
Hi, bug have been fixed https://github.com/andrewsegas/instaboost/commit/4e895f990fe8f4ed96654eef6cb5b57a4423c3c4 

Thanks for your attention
