### ISSUE TITLE
Automatically logging itself out

### ISSUE THREAD

**Issue by fombercom** [andrewsegas/instaboost#10]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.11.6

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (1,2,3,4 or 5)?  1
- [ ] instaboost.py
- [ ] Other

## Python Version?
3

## Description

Type the description of your issue here.
When running, it works for a while then logs itself out.. this is what it displays (have renamed 'example.py' to 'clubs.py' 

Traceback (most recent call last):
  File "clubs.py", line 77, in <module>
    bot.new_auto_mod()
  File "/Users/georgetyson/Desktop/instaboost-master/instaboost/src/instabot.py", line 770, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/georgetyson/Desktop/instaboost-master/instaboost/src/instabot.py", line 852, in new_auto_mod_comments
    nshortcode = self.media_by_tag[0]['code']
IndexError: list index out of range
11:21 Tentando Unfollow: 237471232
11:21 Unfollow: 237471232 #3 of 2.
11:21 Pausing for 16 seconds... 3 of 2
11:21 Logout: likes - 14, follow - 2, unfollow - 3, comments - 0.
11:21 Bot work time: 0:11:59.994023
11:21 Logout success!

Not sure why it's doing this?? 
```
Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
Hi, I got the error, may you update?
c74cba069f2fd23b275e0f3bdfde9b867e9a1ba8
after that, can you test and close the task if it works?

**Comment by fombercom** [comment]
What does the line XXXXXXX Except on get_media! XXXXXXX mean? .. Should this happen? I don't remember seeing it before. 

19.03.2018 10:28
10:28 Checking user info..
10:28 Follower : 1483
10:28 Following : 2903
10:28 Media : 1049
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are following this account
10:28 ======> Get media id by user: p4panda <======
10:28 XXXXXXX Except on get_media! XXXXXXX
10:30 uncharted_uk : Get user info 
19.03.2018 10:30
10:30 Checking user info..
10:30 Follower : 1483
10:30 Following : 2903
10:30 Media : 1049
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are following this account
10:30 ======> Get media id by user: p4panda <======
10:30 XXXXXXX Except on get_media! XXXXXXX

**Comment by fombercom** [comment]
Just realised it's repeatedly targeting the same user.. :'(

**Comment by fombercom** [comment]
I have re-downloaded instaboost and it's working fine now. Must have messed with one of the parameters. My bad.

**Comment by DevinTyler26** [comment]
I am getting the "XXXXXXX Except on get_media! XXXXXXX" when running on Mode 2. Any fixes for this?

**Comment by DevinTyler26** [comment]
@andrewsegas Sounds good! Thank you
