### ISSUE TITLE
Not liked: 400

### ISSUE THREAD

**Issue by socialdom** [andrewsegas/instaboost#11]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [X] I have searched for other issues with the same problem.

## Hosting
- [X] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Running Mode
- [ ] instaboost.exe
- [X] example.py , mode (0)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
3

## Description
Everything worked fine for a while and then it started going to Not liked: 400 after a few hours, now it does within a few minutes and just continues as this.

```
Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
You were temporarily blocked, change the quantity of likes, follow per day!

**Comment by andrewsegas** [comment]
Please, can you try again, this error was fixed
