### ISSUE TITLE
On Ubuntu VPS

### ISSUE THREAD

**Issue by zhmrab** [andrewsegas/instaboost#11]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Is it a local machine?
No
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Linux
## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode 2
- [ ] instaboost.py
- [ ] Other

## Python Version?
2.7

## Description

Type the description of your issue here.
Trying to run this on and Ubuntu VPS but keep on getting Login error! Connection error! and then an alert on IG

How can I fix it so I can have the bot running on vps?

```
Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
Have you tried to login in your browser? In this vps

**Comment by zhmrab** [comment]
Yes and it gives me a warning for suspicious connection, bot works locally though but can’t get a connection on VPS

**Comment by andrewsegas** [comment]
The problem is not in instaboost. Famous
VPS like Google, Amazon etc are obvious suspicious IP for any social network server.

**Comment by andrewsegas** [comment]
@zhmrab you can try to use different proxy, you can set the parameter "proxy"

**Comment by zhmrab** [comment]
@andrewsegas Ok thanks will try the proxy now, on a VPS it follows and unfollows but doesnt like 

Not Liked : 400 is the error
