### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by axellpetrov** [andrewsegas/instaboost#2]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Is it a local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Running Mode
- [x] instaboost.exe
- [ ] example.py , mode (1,2,3,4 or 5)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / 3

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```

**Comment by axellpetrov** [comment]
o que disse, machista?

**Comment by andrewsegas** [comment]
working on it

**Comment by randhipp** [comment]
from https://github.com/instabot-py/instabot.py/issues/1211#issuecomment-382552305 

in your **instabot.py** file. ( in src folder ) Please modify **Line 319** to **"self.user_id = self.user_login"**

JSON Error is gone but another error still happening 

`19.04.2018 13:35`
`13:35 Checking user info..`
`13:35 Except on get_info!`
`13:35 xxxxxxxxxxxxxx : Get user info`

> Traceback (most recent call last):
  File "/root/instaboost/jdboost/Instaboost/src/user_info.py", line 20, in get_user_info
    user_info = json.loads(r.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by andrewsegas** [comment]
Fixed guys
48fe8bd0967d736d2385e62a94c7384e9e76d99a
may you update
