### ISSUE TITLE
Report in errors.log 

### ISSUE THREAD

**Issue by JoeFertig** [andrewsegas/instaboost#2]
Hello & thanks for the awesome work!
After starting the bot I found some entries in the "errors.log" file. Can you explain me what that means and if everything is fine with that?

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ink361.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ink361.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): ink361.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ink361.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com

**Comment by andrewsegas** [comment]
per now it's ok, I'll check later some exception problems
