### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by dvbebber** [andrewsegas/instaboost#21]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode 1
- [x] instaboost.py
- [ ] Other

## Python Version?
2 / 3

## Description

I get the error "ModuleNotFoundError: No module named 'requests'" on both example.py and instaboost.py.
I'm running python 2 and 3, neither works

```
Include the contents of the error.log here (if applicable).
```

**Comment by dvbebber** [comment]
EDIT: If I login using "sudo python example.py" I can like, but it sais "There seems nobody to unfollow"

**Comment by andrewsegas** [comment]
first problem, you need to read the instructions, please run "python install -r requirements.txt" like the instructions in README.RM
the second problem "there seems nobody to unfollow" do follow anyone? make sure that your account is following someone

**Comment by dvbebber** [comment]
Hey bro, thanks for the advise. Problem is, that I already have both the requirements installed and set up everything according to the readme file. I am following about 100 users more than my whitelist, so there definitely is somebody to unfollow, that's why I asked ;)

**Comment by dvbebber** [comment]
So, the "sudo python3 instaboost.py" seems to work so far, but still the same "nobody to unfollow" message. Is it possible, that the bot only unfollows users it started following itself? I switched from the instabot.py to your bot because of the unfollow issue over there. Could that be the point? I only added some users to the unfollow whitelist but there are many more followed that are not on the list. I even tried without users on the whitelist. (My whitelist looks like 'user1', 'user2', ...)

**Comment by dvbebber** [comment]
Update: just realized that the bot seems to unfollow 1 account though, but it still stops with the message

**Comment by dvbebber** [comment]
Solved: The bot only unfollows user it started following. Great work, Andrew! Especially the graphic interface is a nice feature! :) 
Closing the thread now.

**Comment by andrewsegas** [comment]
Hi man, thanks.
If you want to restart this list and start to use a new unfollow list respecting what was in white_list you can just DELETE the file follows_db.db
If you're using the bot for a long time, delete this file, it will be better :)
