### ISSUE TITLE
Tag Blacklist not working

### ISSUE THREAD

**Issue by limerick11** [andrewsegas/instaboost#25]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Raspbian 2018-03-13

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode 0
- [ ] instaboost.py
- [ ] Other

## Python Version?
2.7.9

## Description
I have the following blacklist in my .py file, but bot is still liking photos with tags in the blacklist.

tag_blacklist=['instalike', 'like4like', 'endorse', 'l4l', 'followme', 'instalike', 'tagsforlikes', 'follow', 'thc', 'cannabis', 'featureme', 'like4like', 'likeforfollow', 'glamour', 'ad', 'girl', 'model', 'investment', 'iifym', 'fitness', 'netflixandchill'],
    
I do see the following recurring in my in my log file a few times: Not liked: 400

**Comment by limerick11** [comment]
@andrewsegas can you help me with this issue?

**Comment by andrewsegas** [comment]
@limerick11 , this tag_blacklist is for "likes" not for follow, if you want to use for follow you have unwanted_username_list and anyway you'll need to change your code. This feature is just in the code as example, you need to use it. If you change the code in a good way you can make a pull request here :)

**Comment by limerick11** [comment]
@andrewsegas Yes, I'm only liking and not commenting. I still see photos that have the blacklist hashtag being liked.
Example: https://instagram.com/p/pwi1Gtsrkn/
#followme and #like4like are 2 tags that are in the post and also in my blacklist.

**Comment by andrewsegas** [comment]
@limerick11 Now it's working, please update Instaboost
33233873a67749a5ca92ee2e50c91552107fe386
After your test, please close this issue.
Thanks

**Comment by limerick11** [comment]
@andrewsegas Looks good, thanks! Really appreciate it!
