### ISSUE TITLE
error, cant run bot

### ISSUE THREAD

**Issue by canceroyer** [andrewsegas/instaboost#3]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 8

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (0)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
3

## Description

Type the description of your issue here.

It is not loggin in it prompt this error

Include the contents of the error.log here (if applicable).
 Microsoft Windows [Versión 10.0.16299.371]
(c) 2017 Microsoft Corporation. Todos los derechos reservados.

C:\Users\Gleydys>cd  C:\Users\Gleydys\Desktop\instaboost-master\Instaboost

C:\Users\Gleydys\Desktop\instaboost-master\Instaboost>python example.py
10:39 Instaboost v2.19.0 started at 17.04.2018 10:39:

10:39 Trying to login as ptywear...

Traceback (most recent call last):
  File "example.py", line 59, in <module>
    UI = False)
  File "C:\Users\Gleydys\Desktop\instaboost-master\Instaboost\src\instabot.py", line 241, in __init__
    self.login()
  File "C:\Users\Gleydys\Desktop\instaboost-master\Instaboost\src\instabot.py", line 319, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Gleydys\Desktop\instaboost-master\Instaboost\src\userinfo.py", line 43, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\Gleydys\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Gleydys\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Gleydys\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\Gleydys\Desktop\instaboost-master\Instaboost>

**Comment by andrewsegas** [comment]
working on it

**Comment by Temposchwelle** [comment]
same here :/

**Comment by franciscoarruda** [comment]
I can't run too :(

**Comment by andrewsegas** [comment]
Fixed guys
48fe8bd
may you update

**Comment by Temposchwelle** [comment]
now i have connection error :/

**Comment by andrewsegas** [comment]
@Temposchwelle is your instaboost updated? please check it, here it works!
Which error?

**Comment by Temposchwelle** [comment]
@andrewsegas after update I got connection error now I waited a few hours and tried again and now the fix works so thank you :). But don't know why waiting helped after the update
