### ISSUE TITLE
Suddenly not working

### ISSUE THREAD

**Issue by canceroyer** [andrewsegas/instaboost#30]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (1,2,3,4 or 5)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / 3

## Description

Type the description of your issue here.

it worked all night lon i closed it and opened it again and not working anymore
![instaboost](https://user-images.githubusercontent.com/37394638/38148102-a1863f9c-341a-11e8-9e5c-bb35af10d609.png)

Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
Im sorry everybody, It was MY mistake, now´it will work, Just the Version control was out and without "try - catch".
Try now, and it will work, please close the task if it solved

**Comment by andrewsegas** [comment]
please update the last commit
5009157e9432c248cd5df24c66c5e547d98772ec
