### ISSUE TITLE
Login Error! Connection Error!

### ISSUE THREAD

**Issue by avax123** [andrewsegas/instaboost#4]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Running Mode
- [x] instaboost.exe
- [x] example.py , mode (1,2,3,4 or 5)?
- [x] instaboost.py
- [ ] Other

## Python Version?
2 / 3

## Description

I have issues with connection, log says "Connection error! Login error". I can not understand what's the matter, because my login and password are correct, but instaboost don't working.
error.log - clear
```

**Comment by yigithanyigit** [comment]
ı have a same problem

**Comment by avax123** [comment]
Instaboost founder can't help, nice (not nice)

**Comment by andrewsegas** [comment]
@avax123 @yigithanyigit 
Guys, the problem is not in instaboost. Try to log in your instagram account in your browser, sometimes instagram ask phone number or something like this and it's impossible to know just in instaboost.
so, after log in your account in your browser, try to use instaboost.

**Comment by avax123** [comment]
its true, sry, i'am idiot

**Comment by andrewsegas** [comment]
guys, did u get?

**Comment by avax123** [comment]
yep, thx bro
