### ISSUE TITLE
Login Error! on Google Cloud Compute Engine.

### ISSUE THREAD

**Issue by yigithanyigit** [andrewsegas/instaboost#6]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Is it a local machine?
- [x] Is it google cloud compute engine

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / (Linux) / Android

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (1,2,3,4 or 5)? --"mode=0"
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / (3)

## Description

Type the description of your issue here.

example.py is succesfully running on local windows machine in same settings but its not working on my debian 9 google cloud compute engine.

```
Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
Try to use proxy, the problem is that google cloud computer, amazon and others are suspicious ip for instagram and they bann the access

**Comment by yigithanyigit** [comment]
I will try free proxys on app its not changed.

example : "139.255.57.32:8080" ---> is anonymus free proxy on Indonesia 
I tried something like this but not changed...    

suggestions ?


Thank You.

**Comment by slightlycasual** [comment]
I'm having this same issue and can't get the proxy to work with PIA. Any help would be great!
