### ISSUE TITLE
Key error user

### ISSUE THREAD

**Issue by hannahcho** [andrewsegas/instaboost#7]
Receiving the following error on a windows prompt when entering the 
python example.py command

![image](https://user-images.githubusercontent.com/26803721/37493280-d53f8326-287a-11e8-8542-a3ca28f01b27.png)

**Comment by hannahcho** [comment]
Added this to the instabot.py file

![image](https://user-images.githubusercontent.com/26803721/37493779-8616442c-287c-11e8-918e-a5c61c8b68d8.png)

**Comment by andrewsegas** [comment]
@hannahcho thank you for your help, but i think this problem is in userinfo.py, soon i have time i'll update, or... it's an open source guys :)

**Comment by andrewsegas** [comment]
@hannahcho sorry, you were right, it's in instabot

**Comment by andrewsegas** [comment]
Hi guys,
Already solved here b0b9983996788715a9e99a7c584aa1f83d8eb74f
Please close the issue
